import React, { FC, PropsWithChildren } from "react";
import Head from 'next/head';
import { Layout } from 'antd';
import AppProvider from '@/providers/AppProvider';
import { ContentMainLayout, RootLayout, MainLayoutContainer } from './styles';

const MainLayout: FC<PropsWithChildren<{}>> = ({ children }) => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainLayoutContainer>

                <AppProvider>

                    <RootLayout>

                        <Layout>

                            <ContentMainLayout className="site-layout-background">

                                { children }

                            </ContentMainLayout>

                        </Layout>

                    </RootLayout>

                </AppProvider>

            </MainLayoutContainer>
        </>
    )
}

export default MainLayout;