export const enum ACTIONS {
    JOIN = 'join',
    LEAVE = 'leave',
    SHARE_ROOMS = 'share-rooms',
    ADD_PEER = 'add-peer',
    REMOVE_PEER = 'remove-peer',
    GET_ROOMS = 'get-rooms',
    RELAY_SDP = 'relay-sdp',
    RELAY_ICE = 'relay-ice',
    ICE_CANDIDATE = 'ice-candidate',
    SESSION_DESCRIPTION = 'session-description',
    CLIENT_READY_CONNECT = 'client_ready_connect',
    ERROR_ROOM_CONNECTION = 'error_room_connection',
    SUCCESS_ROOM_CONNECTION = 'success_room_connection',
}